# Generated by Django 5.2.16 on 2026-07-28 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakery', '0003_finishedgoodsstock_is_demo_productionbatch_is_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEventExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='export_id')),
                ('status', models.CharField(choices=[('created', 'создан'), ('sending', 'отправляется'), ('accepted', 'принят'), ('partially_accepted', 'частично принят'), ('failed', 'ошибка')], db_index=True, default='created', max_length=32, verbose_name='статус')),
                ('events_count', models.PositiveIntegerField(default=0, verbose_name='событий')),
                ('file_name', models.CharField(blank=True, max_length=180, verbose_name='имя файла')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='попытки')),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP статус')),
                ('response_body', models.TextField(blank=True, verbose_name='ответ')),
                ('csv_content', models.TextField(blank=True, verbose_name='последний CSV')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'экспорт Process Mining',
                'verbose_name_plural': 'экспорты Process Mining',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='event_id')),
                ('case_id', models.CharField(db_index=True, max_length=120, verbose_name='case_id')),
                ('case_type', models.CharField(choices=[('batch', 'партия'), ('order', 'заказ'), ('problem', 'проблема'), ('shipment', 'отгрузка')], db_index=True, max_length=40, verbose_name='тип процесса')),
                ('activity', models.CharField(max_length=180, verbose_name='действие')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='произошло')),
                ('from_stage', models.CharField(blank=True, max_length=80, verbose_name='от этапа')),
                ('to_stage', models.CharField(blank=True, max_length=80, verbose_name='к этапу')),
                ('status', models.CharField(blank=True, max_length=80, verbose_name='статус бизнес-объекта')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='количество')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='единица')),
                ('problem_type', models.CharField(blank=True, max_length=180, verbose_name='тип проблемы')),
                ('resource', models.CharField(blank=True, max_length=180, verbose_name='ресурс')),
                ('event_data', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('export_status', models.CharField(choices=[('pending', 'ожидает'), ('processing', 'обработка'), ('sent', 'отправлено'), ('failed', 'ошибка'), ('dead_letter', 'dead letter')], db_index=True, default='pending', max_length=24, verbose_name='статус экспорта')),
                ('export_attempts', models.PositiveIntegerField(default=0, verbose_name='попытки')),
                ('exported_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя попытка')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_events', to='bakery.productionbatch', verbose_name='партия')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_events', to='bakery.productionorder', verbose_name='заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_events', to='bakery.product', verbose_name='продукт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_events', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('export', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='process_mining.processeventexport', verbose_name='экспорт')),
            ],
            options={
                'verbose_name': 'событие Process Mining',
                'verbose_name_plural': 'события Process Mining',
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['case_id', 'occurred_at'], name='process_min_case_id_e99869_idx'), models.Index(fields=['export_status', 'created_at'], name='process_min_export__f4e712_idx')],
            },
        ),
    ]
