# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='номер карты')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('overall_result', models.CharField(choices=[('conforming', 'Соответствует'), ('conforming_with_comments', 'Соответствует с замечаниями'), ('reinspection_required', 'Требуется повторный контроль'), ('correction_required', 'Требуется исправление'), ('rejected', 'Забраковано'), ('deviation_approved', 'Отклонение разрешено'), ('incomplete', 'Не завершено')], default='incomplete', max_length=40, verbose_name='результат')),
                ('comments', models.TextField(blank=True, verbose_name='комментарий')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='утверждено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершена'), ('approved', 'Утверждена')], db_index=True, default='draft', max_length=24, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cards', to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('control_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlpost', verbose_name='пост')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='контролёр')),
                ('quality_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='quality.qualityobject', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'карта контроля',
                'verbose_name_plural': 'карты контроля',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspections/', verbose_name='файл')),
                ('file_type', models.CharField(max_length=40, verbose_name='тип файла')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='название')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
                ('inspection_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inspections.inspectioncard', verbose_name='карта')),
            ],
            options={
                'verbose_name': 'файл карты',
                'verbose_name_plural': 'файлы карт',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='числовое значение')),
                ('text_value', models.TextField(blank=True, verbose_name='текст')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='да/нет')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('choice_value', models.CharField(blank=True, max_length=160, verbose_name='выбор')),
                ('conformity_value', models.BooleanField(blank=True, null=True, verbose_name='соответствует')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('is_within_tolerance', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='в допуске')),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='ручное изменение')),
                ('override_reason', models.TextField(blank=True, verbose_name='причина override')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('inspection_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.inspectioncard', verbose_name='карта')),
                ('measuring_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.measuringequipment', verbose_name='средство измерения')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlparameter', verbose_name='параметр')),
                ('template_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.inspectiontemplateparameter', verbose_name='параметр шаблона')),
            ],
            options={
                'verbose_name': 'результат измерения',
                'verbose_name_plural': 'результаты измерений',
                'ordering': ['template_parameter__sequence'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='номер задания')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=16, verbose_name='приоритет')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='плановое начало')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='срок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='завершено')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('assigned', 'Назначено'), ('in_progress', 'В работе'), ('overdue', 'Просрочено'), ('awaiting_reinspection', 'Ожидает повторного контроля'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], db_index=True, default='new', max_length=32, verbose_name='статус')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='просрочено')),
                ('created_automatically', models.BooleanField(default=False, verbose_name='создано автоматически')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('control_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlpost', verbose_name='пост')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('inspection_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.inspectiontemplate', verbose_name='шаблон')),
                ('quality_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quality.qualityobject', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'задание на контроль',
                'verbose_name_plural': 'задания на контроль',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspectioncard',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='inspections.inspectiontask', verbose_name='задание'),
        ),
        migrations.CreateModel(
            name='Reinspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=40, unique=True, verbose_name='номер')),
                ('result', models.CharField(choices=[('passed', 'Положительно'), ('failed', 'Отрицательно'), ('pending', 'Ожидает')], default='pending', max_length=16, verbose_name='результат')),
                ('comments', models.TextField(blank=True, verbose_name='комментарий')),
                ('performed_at', models.DateTimeField(blank=True, null=True, verbose_name='выполнено')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='контролёр')),
                ('new_inspection_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectiontask', verbose_name='новое задание')),
            ],
            options={
                'verbose_name': 'повторный контроль',
                'verbose_name_plural': 'повторный контроль',
                'ordering': ['-id'],
            },
        ),
    ]
