# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('nonconformities', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinspection',
            name='nonconformity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinspections', to='nonconformities.nonconformity', verbose_name='несоответствие'),
        ),
        migrations.AddField(
            model_name='reinspection',
            name='original_inspection_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_reinspections', to='inspections.inspectioncard', verbose_name='исходная карта'),
        ),
        migrations.AddField(
            model_name='reinspection',
            name='quality_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.qualityobject', verbose_name='объект'),
        ),
        migrations.AlterUniqueTogether(
            name='inspectionresult',
            unique_together={('inspection_card', 'template_parameter')},
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['quality_object', 'control_post', 'status'], name='inspections_quality_613fab_idx'),
        ),
    ]
