# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор QMS'), ('quality_manager', 'Руководитель службы качества'), ('quality_engineer', 'Инженер по качеству'), ('inspector', 'Контролёр ОТК'), ('master', 'Производственный мастер'), ('executor', 'Ответственный исполнитель'), ('director', 'Руководитель предприятия'), ('auditor', 'Аудитор')], default='inspector', max_length=32, verbose_name='роль')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.department', verbose_name='подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
    ]
