# Generated by Django 5.2.16 on 2026-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('production_dispatcher', 'Диспетчер производства'), ('technologist', 'Технолог'), ('mixing_operator', 'Оператор замеса'), ('forming_operator', 'Оператор формовки'), ('proofing_operator', 'Оператор расстойки'), ('oven_operator', 'Оператор печи'), ('warehouse_worker', 'Складской сотрудник'), ('manager', 'Руководитель'), ('auditor', 'Аудитор'), ('quality_manager', 'Руководитель службы качества'), ('quality_engineer', 'Инженер по качеству'), ('inspector', 'Контролёр ОТК'), ('master', 'Производственный мастер'), ('executor', 'Ответственный исполнитель'), ('director', 'Руководитель предприятия')], default='mixing_operator', max_length=32, verbose_name='роль'),
        ),
    ]
