# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='действие')),
                ('model_name', models.CharField(max_length=120, verbose_name='модель')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=240, verbose_name='объект')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='изменения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'журнал аудита',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='ID объекта')),
                ('previous_status', models.CharField(blank=True, max_length=80, verbose_name='предыдущий статус')),
                ('new_status', models.CharField(max_length=80, verbose_name='новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='изменено')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='тип объекта')),
            ],
            options={
                'verbose_name': 'история статуса',
                'verbose_name_plural': 'история статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
