# Generated by Django 5.2.16 on 2026-07-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessage',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='ID запроса клиента'),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='уверенность'),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='external_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ID задачи Process Mining'),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='обработано'),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='processing_error',
            field=models.TextField(blank=True, verbose_name='ошибка обработки'),
        ),
        migrations.AlterField(
            model_name='voicemessage',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'ожидает'), ('uploaded', 'загружено'), ('sent', 'отправлено'), ('processing', 'обработка'), ('completed', 'завершено'), ('failed', 'ошибка')], default='uploaded', max_length=32, verbose_name='статус транскрибации'),
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('intent', models.CharField(choices=[('move_batch', 'передать партию'), ('pause_batch', 'остановить партию'), ('resume_batch', 'возобновить партию'), ('create_problem', 'создать проблему'), ('accept_to_warehouse', 'принять на склад'), ('complete_batch', 'завершить партию'), ('add_comment', 'добавить комментарий')], max_length=40, verbose_name='намерение')),
                ('extracted_data', models.JSONField(default=dict, verbose_name='извлечённые данные')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='уверенность')),
                ('status', models.CharField(choices=[('detected', 'распознана'), ('needs_review', 'требует проверки'), ('confirmed', 'подтверждена'), ('executed', 'выполнена'), ('rejected', 'отклонена'), ('failed', 'ошибка')], default='detected', max_length=24, verbose_name='статус')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='выполнено')),
                ('error_message', models.TextField(blank=True, verbose_name='ошибка')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_voice_commands', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил')),
                ('voice_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command', to='bakery.voicemessage', verbose_name='голосовое сообщение')),
            ],
            options={
                'verbose_name': 'голосовая команда',
                'verbose_name_plural': 'голосовые команды',
                'ordering': ['-created_at'],
            },
        ),
    ]
