# Generated by Django 5.2.16 on 2026-07-28 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_voicemessage_client_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='демо'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='демо'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='демо'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='демо'),
        ),
        migrations.CreateModel(
            name='KanbanDemoRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(default='Kanban demo', max_length=160, verbose_name='название')),
                ('status', models.CharField(choices=[('created', 'создано'), ('running', 'запущено'), ('paused', 'пауза'), ('completed', 'завершено'), ('stopped', 'остановлено'), ('failed', 'ошибка')], db_index=True, default='created', max_length=24, verbose_name='статус')),
                ('mode', models.CharField(choices=[('sequential', 'по очереди'), ('wave', 'группами'), ('random', 'случайно'), ('fast', 'быстро')], default='wave', max_length=24, verbose_name='режим')),
                ('total_batches', models.PositiveIntegerField(default=100, verbose_name='всего партий')),
                ('completed_batches', models.PositiveIntegerField(default=0, verbose_name='готово партий')),
                ('speed_seconds', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='скорость, секунд')),
                ('simulate_pauses', models.BooleanField(default=False, verbose_name='симулировать паузы')),
                ('simulate_problems', models.BooleanField(default=False, verbose_name='симулировать проблемы')),
                ('simulate_returns', models.BooleanField(default=False, verbose_name='симулировать возвраты')),
                ('last_error', models.TextField(blank=True, verbose_name='последняя ошибка')),
                ('client_request_id', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='ID запроса клиента')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='старт')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='пауза')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='финиш')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_demo_runs', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'демо Kanban',
                'verbose_name_plural': 'демо Kanban',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='finishedgoodsstock',
            name='demo_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='bakery.kanbandemorun', verbose_name='демо-запуск'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='demo_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='bakery.kanbandemorun', verbose_name='демо-запуск'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='demo_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bakery.kanbandemorun', verbose_name='демо-запуск'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='demo_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='bakery.kanbandemorun', verbose_name='демо-запуск'),
        ),
    ]
