# Generated by Django 5.2.17 on 2026-08-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_backfill_card_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='порядок')),
                ('status', models.CharField(choices=[('available', 'работает'), ('repair', 'ремонт')], default='available', max_length=16, verbose_name='состояние')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активно')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='bakery.productionstage', verbose_name='этап')),
            ],
            options={
                'verbose_name': 'производственное устройство',
                'verbose_name_plural': 'производственные устройства',
                'ordering': ['stage__sequence', 'sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='bakery.productionunit', verbose_name='устройство'),
        ),
        migrations.AddConstraint(
            model_name='productionunit',
            constraint=models.UniqueConstraint(fields=('stage', 'name'), name='unique_production_unit_name_per_stage'),
        ),
    ]
