# Generated by Django 5.2.17 on 2026-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_forecast_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='board_cleared_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='убрано с доски'),
        ),
    ]
