# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='название')),
                ('equipment_type', models.CharField(max_length=120, verbose_name='тип')),
                ('serial_number', models.CharField(max_length=120, unique=True, verbose_name='серийный номер')),
                ('inventory_number', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='инвентарный номер')),
                ('measurement_range', models.CharField(blank=True, max_length=180, verbose_name='диапазон измерений')),
                ('accuracy_class', models.CharField(blank=True, max_length=80, verbose_name='класс точности')),
                ('last_verification_date', models.DateField(blank=True, null=True, verbose_name='последняя поверка')),
                ('next_verification_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='следующая поверка')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('repair', 'Ремонт'), ('blocked', 'Заблокировано'), ('written_off', 'Списано')], default='available', max_length=24, verbose_name='статус')),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='свидетельство')),
                ('verification_organization', models.CharField(blank=True, max_length=180, verbose_name='организация поверки')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.department', verbose_name='подразделение')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
            ],
            options={
                'verbose_name': 'средство измерения',
                'verbose_name_plural': 'средства измерений',
                'ordering': ['next_verification_date', 'name'],
            },
        ),
    ]
