# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=220, verbose_name='название')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='единица')),
                ('value_type', models.CharField(choices=[('number', 'Число'), ('text', 'Текст'), ('date', 'Дата'), ('boolean', 'Да/нет'), ('choice', 'Выбор'), ('conformity', 'Соответствие'), ('file', 'Файл'), ('photo', 'Фото'), ('conclusion', 'Заключение')], max_length=24, verbose_name='тип значения')),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='номинал')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='нижний допуск')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='верхний допуск')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='знаков после запятой')),
                ('is_required', models.BooleanField(default=True, verbose_name='обязательный')),
                ('method', models.CharField(blank=True, max_length=220, verbose_name='метод')),
                ('criticality', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=16, verbose_name='критичность')),
                ('instruction', models.TextField(blank=True, verbose_name='инструкция')),
                ('requires_photo', models.BooleanField(default=False, verbose_name='требует фото')),
                ('requires_double_check', models.BooleanField(default=False, verbose_name='двойная проверка')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'параметр контроля',
                'verbose_name_plural': 'параметры контроля',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControlRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=220, verbose_name='название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('product_type', models.CharField(blank=True, max_length=120, verbose_name='тип продукции')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'маршрут контроля',
                'verbose_name_plural': 'маршруты контроля',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'вид контроля',
                'verbose_name_plural': 'виды контроля',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='название')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=220, verbose_name='название')),
                ('number', models.CharField(max_length=80, verbose_name='номер')),
                ('revision', models.CharField(blank=True, max_length=40, verbose_name='ревизия')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('file', models.FileField(blank=True, upload_to='protocols/', verbose_name='файл')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'нормативный документ',
                'verbose_name_plural': 'нормативные документы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ControlPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=220, verbose_name='название')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=1, verbose_name='последовательность')),
                ('is_required', models.BooleanField(default=True, verbose_name='обязательный')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('normative_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='норматив, мин')),
                ('escalation_minutes', models.PositiveIntegerField(default=120, verbose_name='эскалация, мин')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('control_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controltype', verbose_name='вид контроля')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.department', verbose_name='подразделение')),
            ],
            options={
                'verbose_name': 'пост контроля',
                'verbose_name_plural': 'посты контроля',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=220, verbose_name='название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('product_type', models.CharField(blank=True, max_length=120, verbose_name='тип продукции')),
                ('version', models.CharField(default='1.0', max_length=30, verbose_name='версия')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='утверждено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('control_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlpost', verbose_name='пост')),
                ('control_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controltype', verbose_name='вид контроля')),
            ],
            options={
                'verbose_name': 'шаблон карты контроля',
                'verbose_name_plural': 'шаблоны карт контроля',
                'ordering': ['control_post__sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ControlRouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='обязательный')),
                ('normative_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='норматив, мин')),
                ('create_next_task_automatically', models.BooleanField(default=True, verbose_name='создавать следующее задание')),
                ('control_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlpost', verbose_name='пост')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='quality.controlroute', verbose_name='маршрут')),
                ('inspection_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.inspectiontemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'этап маршрута',
                'verbose_name_plural': 'этапы маршрута',
                'ordering': ['sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='QualityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('unique_number', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='уникальный номер')),
                ('object_type', models.CharField(choices=[('material_batch', 'Партия материалов'), ('component', 'Комплектующее'), ('part', 'Деталь'), ('assembly', 'Сборочная единица'), ('semifinished', 'Полуфабрикат'), ('module', 'Модуль'), ('finished_product', 'Готовое изделие'), ('package', 'Упаковочная единица')], max_length=32, verbose_name='тип объекта')),
                ('product_name', models.CharField(max_length=220, verbose_name='наименование')),
                ('product_code', models.CharField(blank=True, max_length=80, verbose_name='код продукции')),
                ('characteristic', models.CharField(blank=True, max_length=220, verbose_name='характеристика')),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='партия')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='серийный номер')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='количество')),
                ('unit', models.CharField(default='шт', max_length=30, verbose_name='единица')),
                ('supplier', models.CharField(blank=True, max_length=180, verbose_name='поставщик')),
                ('manufacturer', models.CharField(blank=True, max_length=180, verbose_name='изготовитель')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='дата производства')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='дата поступления')),
                ('warehouse', models.CharField(blank=True, max_length=120, verbose_name='склад')),
                ('related_document_number', models.CharField(blank=True, max_length=120, verbose_name='документ')),
                ('quality_status', models.CharField(choices=[('control_not_required', 'Контроль не требуется'), ('awaiting_control', 'Ожидает контроля'), ('control_in_progress', 'Контроль в работе'), ('conforming', 'Соответствует'), ('conforming_with_comments', 'Соответствует с замечаниями'), ('quarantine', 'Карантин'), ('blocked', 'Заблокирован'), ('correction_required', 'Требуется исправление'), ('awaiting_reinspection', 'Ожидает повторного контроля'), ('rejected', 'Забракован'), ('deviation_approved', 'Разрешено отклонение'), ('ready_for_shipment', 'Готов к отгрузке')], db_index=True, default='awaiting_control', max_length=40, verbose_name='статус качества')),
                ('barcode', models.CharField(blank=True, max_length=120, verbose_name='штрихкод')),
                ('qr_code', models.CharField(blank=True, max_length=120, verbose_name='QR-код')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('current_control_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.controlpost', verbose_name='текущий пост')),
                ('current_route_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.controlroutestep', verbose_name='текущий этап')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.department', verbose_name='подразделение')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.controlroute', verbose_name='маршрут')),
            ],
            options={
                'verbose_name': 'объект контроля',
                'verbose_name_plural': 'объекты контроля',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='порядок')),
                ('lower_limit_override', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='нижний допуск')),
                ('upper_limit_override', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='верхний допуск')),
                ('nominal_value_override', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='номинал')),
                ('is_required_override', models.BooleanField(blank=True, null=True, verbose_name='обязательный')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlparameter', verbose_name='параметр')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='quality.inspectiontemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'параметр шаблона',
                'verbose_name_plural': 'параметры шаблона',
                'ordering': ['sequence'],
                'unique_together': {('template', 'parameter')},
            },
        ),
    ]
