# Generated by Django 5.2.16 on 2026-07-21 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=220, verbose_name='название')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='категория')),
                ('criticality', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=16, verbose_name='критичность')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('repair_allowed', models.BooleanField(default=True, verbose_name='ремонт разрешён')),
                ('process_stop_required', models.BooleanField(default=False, verbose_name='остановка процесса')),
                ('manager_notification_required', models.BooleanField(default=False, verbose_name='уведомить руководителя')),
                ('object_block_required', models.BooleanField(default=False, verbose_name='блокировка объекта')),
                ('recommended_action', models.TextField(blank=True, verbose_name='рекомендуемое действие')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'тип дефекта',
                'verbose_name_plural': 'типы дефектов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NonconformityCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='название')),
                ('category', models.CharField(max_length=120, verbose_name='категория')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
            ],
            options={
                'verbose_name': 'причина несоответствия',
                'verbose_name_plural': 'причины несоответствий',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Nonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, max_length=40, unique=True, verbose_name='номер')),
                ('description', models.TextField(verbose_name='описание')),
                ('criticality', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], max_length=16, verbose_name='критичность')),
                ('affected_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='количество')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='срок')),
                ('decision', models.CharField(blank=True, choices=[('correction', 'Исправление'), ('rework', 'Доработка'), ('repair', 'Ремонт'), ('reinspection', 'Повторный контроль'), ('sorting', 'Сортировка'), ('supplier_return', 'Возврат поставщику'), ('write_off', 'Списание'), ('final_rejection', 'Окончательный брак'), ('deviation_use', 'Использование по отклонению'), ('stop_production', 'Остановить производство'), ('quarantine', 'Карантин')], max_length=32, verbose_name='решение')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрировано'), ('under_review', 'На рассмотрении'), ('assigned', 'Назначено'), ('cause_analysis', 'Анализ причины'), ('correction_in_progress', 'Исправление'), ('awaiting_reinspection', 'Ожидает повторного контроля'), ('resolved', 'Решено'), ('closed', 'Закрыто'), ('rejected', 'Отклонено'), ('overdue', 'Просрочено')], db_index=True, default='registered', max_length=40, verbose_name='статус')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('approved_by_quality_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_critical_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='подтвердил руководитель качества')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='закрыл')),
                ('control_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.controlpost', verbose_name='пост')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonconformities.defecttype', verbose_name='тип дефекта')),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='выявил')),
                ('inspection_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='inspections.inspectioncard', verbose_name='карта')),
                ('quality_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformities', to='quality.qualityobject', verbose_name='объект')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.department', verbose_name='ответственное подразделение')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('suspected_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformities.nonconformitycause', verbose_name='предполагаемая причина')),
            ],
            options={
                'verbose_name': 'несоответствие',
                'verbose_name_plural': 'несоответствия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=40, unique=True, verbose_name='номер')),
                ('title', models.CharField(max_length=220, verbose_name='название')),
                ('temporary_action', models.TextField(blank=True, verbose_name='временное действие')),
                ('root_cause', models.TextField(blank=True, verbose_name='коренная причина')),
                ('root_cause_method', models.CharField(choices=[('five_whys', '5 Why'), ('cause_diagram', 'Диаграмма причин'), ('expert_opinion', 'Экспертная оценка')], default='five_whys', max_length=32, verbose_name='метод анализа')),
                ('action_plan', models.TextField(verbose_name='план действий')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='срок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='выполнено')),
                ('effectiveness_result', models.TextField(blank=True, verbose_name='результат эффективности')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('assigned', 'Назначено'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('effectiveness_check', 'Проверка эффективности'), ('closed', 'Закрыто'), ('overdue', 'Просрочено')], default='planned', max_length=32, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_corrective_actions', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='nonconformities.nonconformity', verbose_name='несоответствие')),
            ],
            options={
                'verbose_name': 'корректирующее действие',
                'verbose_name_plural': 'корректирующие действия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonconformityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='defects/', verbose_name='файл')),
                ('attachment_type', models.CharField(max_length=40, verbose_name='тип')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('nonconformity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='nonconformities.nonconformity', verbose_name='несоответствие')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'файл несоответствия',
                'verbose_name_plural': 'файлы несоответствий',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
