# Generated by Django 5.2.16 on 2026-07-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
        ('nonconformities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformity',
            name='bakery_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='bakery.productionbatch', verbose_name='производственная партия'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='bakery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='bakery.productionorder', verbose_name='заказ хлебозавода'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='bakery_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='bakery.product', verbose_name='продукт'),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='bakery_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformities', to='bakery.productionstage', verbose_name='этап производства'),
        ),
    ]
